global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['192.168.1.101:8080']

  - job_name: 'identity-service'
    static_configs:
      - targets: ['192.168.1.101:8081']

  - job_name: 'catalog-service'
    static_configs:
      - targets: ['192.168.1.101:8082']

  - job_name: 'seating-service'
    static_configs:
      - targets: ['192.168.1.101:8083']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['192.168.1.101:8084']

  - job_name: 'order-service'
    static_configs:
      - targets: ['192.168.1.101:8085']

  - job_name: 'ticket-service'
    static_configs:
      - targets: ['192.168.1.101:8086']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['192.168.1.101:8087']
